package com.example.spring_security_demo.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Entity
@Table(name = "filter_options")
@AllArgsConstructor
@NoArgsConstructor
public class FilterOption {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(nullable = false)
    private String name;

    @ManyToOne
    @JoinColumn(name = "filter_id", referencedColumnName = "id")
    private Filter filter_id;

    //since id is autogenerated we need to create a constructor with 2 parametre
    public FilterOption(String name,Filter filter_id){
        this.name = name;
        this.filter_id = filter_id;
    }
}
